export const data = [
  { title: "acre", value: "acre" },
  { title: "are", value: "are" },
  { title: "bal", value: "bal" },
  { title: "centimeter", value: "centimeter" },
  { title: "cup", value: "cup" },
  { title: "gallon", value: "gallon" },
  { title: "gram", value: "gram" },
  { title: "hektar", value: "hektar" },
  { title: "inchi", value: "inchi" },
  { title: "kilogram", value: "kilogram" },
  { title: "kilometer", value: "kilometer" },
  { title: "kilometer persegi", value: "kilometer_persegi" },
  { title: "kubik meter", value: "kubik_meter" },
  { title: "liter", value: "liter" },
  { title: "meter", value: "meter" },
  { title: "meter persegi", value: "meter_persegi" },
  { title: "miligram", value: "miligram" },
  { title: "mililiter", value: "mililiter" },
  { title: "milimeter", value: "milimeter" },
  { title: "pound", value: "pound" },
  { title: "ton", value: "ton" },
];
